### ISSUE TITLE
Overriding Ecto virtual attributes

### ISSUE THREAD

**Issue by MattNguyen** [batate/blacksmith#15]
For usage with Ecto models, the example given in the readme indicates defining custom save functions like the following: 

```elixir
defmodule Blacksmith.Config do
  def save(map) do
    MyRepo.insert(map)
  end

  def save_all(list) do
    Enum.map(list, &MyRepo.insert/1)
  end
end
```

However, if `map` contains virtual attributes, they will not be included in the changeset since passing a model to `insert/1` will create a changeset with non-virtual attributes. This could be problematic for changeset validations that require virtual attributes. 

My current implementation does some inference from `map`, and then creates the model struct dynamically with `new`, which I define in the model.

```elixir
defmodule Blacksmith.Config do
  def save(repo, map) do
    struct = Map.get(map, :__struct__)
    params = Map.from_struct(map)

    struct.changeset(struct.new, params) # `struct.new` defined on the model
    |> repo.insert
  end

  def save_all(repo, list) do
    Enum.map(list, &repo.insert/1)
  end
end
```

I'd rather not repeat defining `new` for every model, but if I define it in `MyApp.Web.model/0`, I get compilation errors.

At the end of the day, I want to override a virtual attribute when calling `Forge.saved_model Repo`, which requires passing a changeset into `Repo.insert`. How would you suggest I do this?

Thanks in advance!

**Comment by ericmj** [comment]
What does the `new` function do?

**Comment by MattNguyen** [comment]
```elixir
def new do
  %__MODULE__{}
end
```

**Comment by ericmj** [comment]
Then I don't understand the problem, you can do `struct(Map.get(map, :__struct__), Map.from_struct(map))` or just pass `map` directly.

Why do you need to run validations? The model you're inserting should already be valid.
