### ISSUE TITLE
Hex package for 0.2.0 version

### ISSUE THREAD

**Issue by gaynetdinov** [batate/blacksmith#16]
Hi! 

Could you please publish hex package for current version `0.2.0`? Currently last available hex package has version `0.1.3` and some of the features from the `README` don't work with version `0.1.3`. For example, `saved_*/0` function does not exist. 

Thanks!

**Comment by ericmj** [comment]
Version 0.2.0 is still in development. Here are docs for version 0.1.3 http://hexdocs.pm/blacksmith/0.1.3/
